name: .ocmod.zip elkészítése
on: [workflow_dispatch]

jobs:
  zip-n-push:
    name: Zip and Push
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          cd ../
          rm -rf connector-opencart-3.zip
          zip -r connector-opencart-3.ocmod.zip connector-opencart-3/upload/* -x ".git/*" ".github/*"
